export const API_ENDPOINTS = {
  auth: {
    me: '/auth/me',
    login: '/auth/login',
    logout: '/auth/logout',
    register: '/auth/register',
  },
  dashboard: {
    summary: '/dashboard/summary',
    activity: '/dashboard/activity',
  },
  users: {
    profile: '/users/me/profile',
    password: '/users/me/password',
  },
  learning: {
    subjects: '/subjects',
    subject: (id) => `/subjects/${id}`,
    generateCourse: '/subjects/generate',
    lesson: (id) => `/lessons/${id}`,
    completeLesson: (id) => `/lessons/${id}/complete`,
  },
  aiTools: {
    generate: '/ai/study-tools',
    objectivesPreview: '/ai/study-tools/objectives',
  },
  quizzes: {
    generate: '/quizzes/generate',
    quiz: (id) => `/quizzes/${id}`,
    attempts: (id) => `/quizzes/${id}/attempts`,
    history: '/quizzes/history',
    attempt: (id) => `/quizzes/attempts/${id}`,
  },
  chatbot: {
    conversations: '/chat/conversations',
    messages: '/chat',
    history: '/chat/history',
    conversation: (id) => `/chat/${id}`,
    regenerate: (id) => `/chat/${id}/regenerate`,
    suggestedQuestions: '/chat/suggested-questions',
  },
  resources: {
    resources: '/resources',
    resource: (id) => `/resources/${id}`,
    upload: '/resources/upload',
    link: '/resources/link',
    view: (id) => `/resources/${id}/view`,
    download: (id) => `/resources/${id}/download`,
  },
  planner: {
    tasks: '/study-tasks',
    priorities: '/task-priorities',
  },
  analytics: {
    summary: '/analytics/summary',
    studySessions: '/study-sessions',
  },
  notifications: {
    notifications: '/notifications',
    markAllRead: '/notifications/mark-all-read',
  },
  feedback: {
    feedback: '/feedback',
    summary: '/feedback/summary',
    mine: '/feedback/mine',
    entry: (id) => `/feedback/${id}`,
  },
  admin: {
    auditLog: '/admin/audit-log',
    auditLogExport: '/admin/audit-log/export',
    chatSessionUsers: '/admin/chat-sessions/users',
    chatSessionsForUser: (userId) => `/admin/chat-sessions/users/${userId}`,
    chatSession: (id) => `/admin/chat-sessions/${id}`,
    chatSessionArchive: (id) => `/admin/chat-sessions/${id}/archive`,
    chatSessionUnarchive: (id) => `/admin/chat-sessions/${id}/unarchive`,
    dashboard: '/admin/dashboard',
    announcements: '/admin/announcements',
    announcementsList: '/admin/announcements/list',
    announcement: (id) => `/admin/announcements/${id}`,
    announcementArchive: (id) => `/admin/announcements/${id}/archive`,
    announcementUnarchive: (id) => `/admin/announcements/${id}/unarchive`,
    users: '/admin/users',
    user: (id) => `/admin/users/${id}`,
    userResetProgress: (id) => `/admin/users/${id}/reset-progress`,
    resources: '/admin/resources',
    resource: (id) => `/admin/resources/${id}`,
    resourceDownload: (id) => `/admin/resources/${id}/download`,
    resourceArchive: (id) => `/admin/resources/${id}/archive`,
    resourceUnarchive: (id) => `/admin/resources/${id}/unarchive`,
    resourcesBulk: '/admin/resources/bulk',
    feedback: '/admin/feedback',
    feedbackAnalytics: '/admin/feedback/analytics',
    feedbackEntry: (id) => `/admin/feedback/${id}`,
    feedbackArchive: (id) => `/admin/feedback/${id}/archive`,
    feedbackUnarchive: (id) => `/admin/feedback/${id}/unarchive`,
    feedbackRestore: (id) => `/admin/feedback/${id}/restore`,
    learning: '/admin/learning',
    learningCourse: (id) => `/admin/learning/${id}`,
    learningArchive: (id) => `/admin/learning/${id}/archive`,
    learningUnarchive: (id) => `/admin/learning/${id}/unarchive`,
    analytics: '/admin/analytics',
  },
};
